spring:
  application:
    name: seckill-product
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: seckill
        group: DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://mysql:3306/seckill_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    password: redis123456
    database: 0
    timeout: 10000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
  elasticsearch:
    uris: http://elasticsearch:9200
    connection-timeout: 5000ms
    socket-timeout: 60000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.manus.seckill.product.entity

server:
  port: 8082

logging:
  level:
    root: INFO
    com.manus.seckill: DEBUG
